language: python
python:
- '3.6'

cache: pip

services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database challengethree;' -U postgres
script:
- pytest -v --cov app --cov-report
after_success:
- coveralls
