language: python
python:
- '3.6'

services:
  - postgresql
before_script:
- psql -c 'create database challengethree;' -U postgres
install:
- pip3 install -r requirements.txt
script:
- pytest -v --cov app --cov-report term-missing
after_success:
- coveralls
